version: '3.8'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - casca-to-dbdata:/data/db
    networks:
      - app-network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    environment:
      - MONGODB=mongodb://mongodb:27017
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - casca-to-node_modules:/home/node/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  casca-to-dbdata:
  casca-to-node_modules:
